import { Action } from 'redux';
import { ThunkAction } from 'redux-thunk';
import store from './reducers';

export type thunkType = ThunkAction<
  void,
  typeof store,
  unknown,
  Action<string>
>;

// Авторизация
export const SET_USER_DATA = 'SET_USER_DATA'
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
export const LOGOUT_USER = 'LOGOUT_USER'

// Список заявок
export const APPLICATIONS_GET_REQUEST = 'APPLICATIONS_GET_REQUEST'
export const APPLICATIONS_GET_SUCCESS = 'APPLICATIONS_GET_SUCCESS'
export const APPLICATIONS_GET_ERROR = 'APPLICATIONS_GET_ERROR'

// Детали заявки
export const DETAIL_APPLICATIONS_SET = 'DETAIL_APPLICATIONS_SET'
export const DETAIL_PRODUCTS_GET_REQUEST = 'DETAIL_PRODUCTS_GET_REQUEST'
export const DETAIL_PRODUCTS_GET_SUCCESS = 'DETAIL_PRODUCTS_GET_SUCCESS'
export const DETAIL_PRODUCTS_GET_ERROR = 'DETAIL_PRODUCTS_GET_ERROR' 
export const DETAIL_PAYMENTS_GET_REQUEST = 'DETAIL_PAYMENTS_GET_REQUEST'
export const DETAIL_PAYMENTS_GET_SUCCESS = 'DETAIL_PAYMENTS_GET_SUCCESS'
export const DETAIL_PAYMENTS_GET_ERROR = 'DETAIL_PAYMENTS_GET_ERROR'
export const DETAIL_PAYMENT_POST_REQUEST = 'DETAIL_PAYMENT_POST_REQUEST'
export const DETAIL_PAYMENT_POST_SUCCESS = 'DETAIL_PAYMENT_POST_SUCCESS'
export const DETAIL_PAYMENT_POST_ERROR = 'DETAIL_PAYMENT_POST_ERROR'

// Этапы 
export const STAGES_GET_REQUEST = 'STAGES_GET_REQUEST'
export const STAGES_GET_SUCCESS = 'STAGES_GET_SUCCESS'
export const STAGES_GET_ERROR = 'STAGES_GET_ERROR'
export const STAGE_POST_REQUEST = 'STAGE_POST_REQUEST'
export const STAGE_POST_SUCCESS = 'STAGE_POST_SUCCESS'
export const STAGE_POST_ERROR = 'STAGE_POST_ERROR'

// Клиенты 
export const CLIENTS_SEARCH_GET_SUCCESS = 'CLIENTS_SEARCH_GET_SUCCESS'
export const CLIENTS_SEARCH_GET_REQUEST = 'CLIENTS_SEARCH_GET_REQUEST'
export const CLIENTS_SEARCH_GET_ERROR = 'CLIENTS_SEARCH_GET_ERROR' 
export const CLIENTS_GET_REQUEST = 'CLIENT_GET_REQUEST'
export const CLIENTS_GET_SUCCESS = 'CLIENT_GET_SUCCESS'
export const CLIENTS_GET_ERROR = 'CLIENT_GET_ERROR'
export const CLIENTS_POST_SUCCESS = 'CLIENTS_POST_SUCCESS'
export const CLIENTS_POST_REQUEST = 'CLIENTS_POST_REQUEST'
export const CLIENTS_POST_ERROR = 'CLIENTS_POST_ERROR'
export const CLIENTS_DELETE_SUCCESS = 'CLIENTS_DELETE_SUCCESS'
export const CLIENTS_DELETE_REQUEST = 'CLIENTS_DELETE_REQUEST'
export const CLIENTS_DELETE_ERROR = 'CLIENTS_DELETE_ERROR'
export const CLIENTS_CATEGORY_GET_REQUEST = 'CLIENTS_CATEGORY_GET_REQUEST'
export const CLIENTS_CATEGORY_GET_SUCCESS = 'CLIENTS_CATEGORY_GET_SUCCESS'
export const CLIENTS_CATEGORY_GET_ERROR = 'CLIENTS_CATEGORY_GET_ERROR' 
export const CLIENTS_CATEGORY_POST_SUCCESS = 'CLIENTS_CATEGORY_POST_SUCCESS'
export const CLIENTS_CATEGORY_DELETE_SUCCESS = 'CLIENTS_CATEGORY_DELETE_SUCCESS'
export const CLIENTS_CATEGORY_PUT_SUCCESS = 'CLIENTS_CATEGORY_PUT_SUCCESS'


// Компания 
export const COMPANY_GET_REQUEST = 'COMPANY_GET_REQUEST'
export const COMPANY_GET_SUCCESS = 'COMPANY_GET_SUCCESS'
export const COMPANY_GET_ERROR = 'COMPANY_GET_ERROR'